name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.triveniparimi }}" | docker login -u "${{ secrets.Remember2023 }}" --password-stdin

      - name: Build Docker image
        run: docker build -t triveniparimi/fastapi-app:latest .

      - name: Push Docker image
        run: docker push triveniparimi/fastapi-app:latest
